-- hexa-oauth2 (sottosistema login): provider OIDC salvati dalla UI, lista degli utenti ammessi e cancello di accesso (UNA riga, id = 1).
-- Il segreto del client NON e' qui: e' un token di /tokens (provider OAUTH2), cifrato dal core; secret_token_id e' una colonna semplice, senza FK.
CREATE TABLE oauth2_provider (
    id              bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    slug            varchar(30) NOT NULL,
    title           varchar(60) NOT NULL,
    issuer_uri      varchar(300) NOT NULL,
    client_id       varchar(300) NOT NULL,
    secret_token_id bigint NOT NULL,
    created_at      timestamptz NOT NULL,
    CONSTRAINT pk_oauth2_provider PRIMARY KEY (id),
    CONSTRAINT uq_oauth2_provider_slug UNIQUE (slug)
);

-- kind = EMAIL (valore = email esatta) o DOMAIN (valore = dominio, confrontato per uguaglianza con la parte dopo l'ultima chiocciola).
-- issuer/subject: identita' del provider legata al primo accesso di un'email esatta.
CREATE TABLE oauth2_allowed_user (
    id            bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    kind          varchar(10) NOT NULL,
    value         varchar(255) NOT NULL,
    issuer        varchar(255),
    subject       varchar(255),
    created_at    timestamptz NOT NULL,
    last_login_at timestamptz,
    CONSTRAINT pk_oauth2_allowed_user PRIMARY KEY (id),
    CONSTRAINT uq_oauth2_allowed_user_kind_value UNIQUE (kind, value)
);

CREATE TABLE oauth2_gate (
    id                bigint NOT NULL,
    enabled           boolean NOT NULL,
    verified_login_at timestamptz,
    updated_at        timestamptz NOT NULL,
    CONSTRAINT pk_oauth2_gate PRIMARY KEY (id),
    CONSTRAINT ck_oauth2_gate_single_row CHECK (id = 1)
);
