-- AI (hexa-ai): chat (conversazioni, turni, tag) e vector store della ricerca semantica. Si applica dopo il core e PRIMA dell'app (versione a timestamp
-- intermedia). Convenzioni e regola delle versioni: vedi db/migration/core.

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE chat_conversation (
    id         bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title      varchar(255),
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    -- Stato GREZZO del form di generazione dell'host (JSON, come lo salva localStorage) per conversazione: NULL = precedente alla colonna
    -- (alla prima apertura adotta il form del browser e lo salva qui); '{}' = default del catalogo (lo scrive il costruttore dell'entity).
    generation_settings_json text,
    CONSTRAINT pk_chat_conversation PRIMARY KEY (id)
);


-- outcome_ref = riferimento OPACO all'esito avviato dal turno (l'host lo interpreta: l'app lo lega a generation con una FK ON DELETE SET NULL, vedi
-- db/migration/app). La chat non conosce il dominio dell'host.
-- error = turno ASSISTANT di errore (escluso dal contesto inviato all'LLM).
CREATE TABLE chat_message (
    id              bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    conversation_id bigint NOT NULL,
    role            varchar(20) NOT NULL,
    content         text NOT NULL,
    outcome_ref     bigint,
    error           boolean NOT NULL DEFAULT FALSE,
    created_at      timestamptz NOT NULL,
    CONSTRAINT pk_chat_message PRIMARY KEY (id),
    CONSTRAINT fk_chat_message_conversation FOREIGN KEY (conversation_id) REFERENCES chat_conversation (id)
);

-- Tag utente di una conversazione (tag di hexa-ai; i tag delle generazioni sono dell'app).
CREATE TABLE chat_conversation_tag (
    conversation_id bigint       NOT NULL,
    tag             varchar(255) NOT NULL,
    CONSTRAINT pk_chat_conversation_tag PRIMARY KEY (conversation_id, tag),
    CONSTRAINT fk_chat_conversation_tag_conversation FOREIGN KEY (conversation_id) REFERENCES chat_conversation (id) ON DELETE CASCADE
);
CREATE INDEX idx_chat_conversation_tag_tag ON chat_conversation_tag (tag);

-- Vector store della ricerca semantica (PgVectorStore di Spring AI, vedi CLAUDE.md "Ricerca semantica"): schema imposto dallo
-- store (id, content, metadata, embedding). id text perche' gli id sono "generation:12", "note:<uuid>". vector(384) = dimensione di
-- multilingual-e5-small: un modello con altre dimensioni richiede una nuova migrazione (ALTER ... TYPE vector(N), dopo aver
-- svuotato la tabella) e la reindicizzazione. NESSUN indice ANN (HNSW/IVFFlat): /search mostra TUTTA la classifica sopra soglia e un
-- indice approssimato tronca i risultati a ef_search (40); lo scan esatto a decine di migliaia di righe costa pochi ms.
-- L'hash del testo, il modello e la data di indicizzazione stanno nei metadata (chiavi riservate, vedi VectorIndexer).
CREATE TABLE vector_store (
    id        text PRIMARY KEY,
    content   text,
    metadata  json,
    embedding vector(384)
);
