-- Addestramento LoRA, tappa 4: le impostazioni di lancio stanno con la BOZZA (si riprende, si cambia qualcosa, si lancia un nuovo training) e lo storico dei
-- training. Ogni training ha il PROPRIO dataset congelato (snapshot: un training_dataset con frozen = true, con le sue immagini e i suoi file), quindi eliminare o
-- modificare la bozza di origine non tocca mai cio' con cui si e' addestrato.

ALTER TABLE training_dataset ADD COLUMN model_name varchar(60);
ALTER TABLE training_dataset ADD COLUMN training_steps integer NOT NULL DEFAULT 1000;
ALTER TABLE training_dataset ADD COLUMN seed bigint;
-- Copia dei pesi su HuggingFace: ACCESA di default e privata. hf_token_id e' l'id di un token salvato in /tokens (niente FK: il core non conosce l'app).
ALTER TABLE training_dataset ADD COLUMN hf_publish boolean NOT NULL DEFAULT true;
ALTER TABLE training_dataset ADD COLUMN hf_token_id bigint;
ALTER TABLE training_dataset ADD COLUMN hf_repo_name varchar(96);
ALTER TABLE training_dataset ADD COLUMN hf_private boolean NOT NULL DEFAULT true;

CREATE TABLE training (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- FK solo verso il dataset congelato (stesso esagono): il training lo possiede e lo elimina con se'. La bozza di origine puo' sparire: niente FK.
    snapshot_dataset_id bigint       NOT NULL REFERENCES training_dataset (id),
    source_dataset_id   bigint,
    -- Copia di cio' che serve all'elenco senza leggere lo snapshot con tutte le sue immagini.
    name                varchar(80)  NOT NULL,
    trigger_word        varchar(40)  NOT NULL,
    lora_type           varchar(20)  NOT NULL,
    image_count         integer      NOT NULL,
    external_id         varchar(100),
    trainer_version     varchar(100),
    destination_owner   varchar(100),
    destination_name    varchar(100),
    status              varchar(20)  NOT NULL,
    error_message       text,
    logs                text,
    training_steps      integer      NOT NULL,
    seed                bigint,
    -- MAI il token: solo se si e' chiesta la copia, il repo (utente/nome) e se esiste davvero.
    hf_publish          boolean      NOT NULL DEFAULT false,
    hf_repo_id          varchar(200),
    hf_status           varchar(20)  NOT NULL DEFAULT 'NONE',
    preset_id           bigint,
    predict_time_seconds double precision,
    created_at          timestamptz  NOT NULL,
    completed_at        timestamptz
);

CREATE INDEX ix_training_created_at ON training (created_at DESC);
CREATE INDEX ix_training_status ON training (status);
