-- APP: tabella della slice di esempio (si cancella insieme a `example/`). Le versioni sono timestamp e vanno SEMPRE dopo quelle del core (1200) e di hexa-ai (1210);
-- Flyway fonde tutte le sottocartelle di db/migration. Dialetto: identificatori minuscoli non quotati, timestamptz, enum Java = varchar.
CREATE TABLE example_item (
    id         bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title      varchar(255) NOT NULL,
    created_at timestamptz NOT NULL,
    CONSTRAINT pk_example_item PRIMARY KEY (id)
);
