-- CORE: schema dei sottosistemi riusabili (eventi di sistema, token API). Le tabelle dell'app stanno in db/migration/app.
-- Versioni A TIMESTAMP in entrambe le location (core e app): Flyway le fonde in un'unica sequenza ordinata e con outOfOrder=false
-- una versione core piu' vecchia della piu' recente gia' applicata (anche dell'app) fallirebbe in validazione. Per ogni nuova
-- migrazione: V<aaaa_mm_gg_hhmm>__descrizione.sql, mai riusare ne' modificare un file gia' eseguito (il checksum fa fallire l'avvio).
--
-- Convenzioni: identificatori minuscoli NON quotati (Hibernate non li quota); testo lungo = text; timestamp = timestamptz;
-- gli "enum" Java sono varchar (nessun ENUM/CHECK di DB: un nuovo valore non richiede una migrazione).

-- Registro eventi di sistema (errori e avvisi), pagina /system/events. Nessuna FK verso le tabelle dell'app: l'evento deve
-- sopravvivere alla cancellazione dell'entita' a cui si riferisce (che e' descritta dal solo subject). Serie = ripetizioni ravvicinate dello stesso evento
-- (occurrences/last_seen_at). subject = a cosa si riferisce (es. 'token:12'); acknowledged_at = visualizzato (campanella).
CREATE TABLE system_event (
    id              bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      timestamptz NOT NULL,
    last_seen_at    timestamptz NOT NULL,
    occurrences     int NOT NULL,
    source          varchar(40) NOT NULL,
    severity        varchar(10) NOT NULL DEFAULT 'ERROR',
    operation       varchar(100) NOT NULL,
    error_type      varchar(200) NOT NULL,
    message         varchar(2000) NOT NULL,
    details         text,
    subject         varchar(100),
    acknowledged_at timestamptz,
    CONSTRAINT pk_system_event PRIMARY KEY (id)
);
CREATE INDEX idx_system_event_last_seen ON system_event (last_seen_at);
CREATE INDEX idx_system_event_severity ON system_event (severity, last_seen_at);
CREATE INDEX idx_system_event_unseen ON system_event (acknowledged_at, last_seen_at);

-- Token API (nome del servizio in provider, es. CIVITAI/HUGGINGFACE): cifrati (SecretCipher), scelti per NOME nelle form. token_hint = ultimi
-- caratteri in chiaro, solo per riconoscerlo nella UI.
CREATE TABLE api_token (
    id              bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    provider        varchar(40) NOT NULL,
    name            varchar(60) NOT NULL,
    token_encrypted bytea NOT NULL,
    token_hint      varchar(8) NOT NULL,
    expires_at      date,
    created_at      timestamptz NOT NULL,
    updated_at      timestamptz NOT NULL,
    CONSTRAINT pk_api_token PRIMARY KEY (id),
    CONSTRAINT uq_api_token_provider_name UNIQUE (provider, name)
);
