-- APP: schema della webapp di generazione immagini (generazioni, catalogo modelli Replicate, LoRA). Si applica
-- dopo core e ai (versione a timestamp piu' recente; le tabelle chat_* e vector_store sono di hexa-ai, db/migration/ai). Storico: squash delle V1..V23 del periodo H2 e delle prime migrazioni Postgres
-- (le versioni originali restano nella storia git). Convenzioni e regola delle versioni: vedi db/migration/core.

-- Una Generation avviata da /deep-chat ricorda la conversazione (NULL per il form diretto): serve a ripristinare il placeholder di
-- una generazione ancora in corso al reload. ON DELETE SET NULL: cancellare la conversazione non elimina le generazioni.
-- source_generation_id = generazione sorgente di un img2video ("Anima"), stesso ragionamento. cost_usd = costo stimato (snapshot,
-- NULL se non stimabile). source_upload_filename = immagine caricata per un img2video/edit stand-alone (non e' una Generation).
CREATE TABLE generation (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    external_id            varchar(255) NOT NULL,
    model                  varchar(255) NOT NULL,
    version                varchar(255),
    prompt                 text NOT NULL,
    parameters_json        text,
    seed                   bigint,
    status                 varchar(20) NOT NULL,
    kind                   varchar(10) NOT NULL DEFAULT 'IMAGE',
    error_message          text,
    cost_usd               numeric(12, 6),
    source_generation_id   bigint,
    source_upload_filename varchar(255),
    conversation_id        bigint,
    created_at             timestamptz NOT NULL,
    completed_at           timestamptz,
    CONSTRAINT pk_generation PRIMARY KEY (id),
    CONSTRAINT fk_generation_source FOREIGN KEY (source_generation_id) REFERENCES generation (id) ON DELETE SET NULL
);

-- File prodotti da una generazione (ordinati) e file con la star (preferiti, per singolo file).
CREATE TABLE generation_image (
    generation_id bigint NOT NULL,
    ordinal       int NOT NULL,
    filename      varchar(255) NOT NULL,
    CONSTRAINT pk_generation_image PRIMARY KEY (generation_id, ordinal),
    CONSTRAINT fk_generation_image_generation FOREIGN KEY (generation_id) REFERENCES generation (id)
);

CREATE TABLE generation_favourite (
    generation_id bigint NOT NULL,
    filename      varchar(255) NOT NULL,
    CONSTRAINT pk_generation_favourite PRIMARY KEY (generation_id, filename),
    CONSTRAINT fk_generation_favourite_generation FOREIGN KEY (generation_id) REFERENCES generation (id) ON DELETE CASCADE
);

-- Catalogo dei modelli Replicate proposti nelle form. form_type seleziona form/handler Java (GenerationFormType), varchar per non
-- richiedere una migrazione di tipo a ogni nuovo form-type (serve solo l'INSERT del seed).
CREATE TABLE replicate_model (
    id          bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner       varchar(255) NOT NULL,
    name        varchar(255) NOT NULL,
    version     varchar(255),
    description varchar(1024),
    form_type   varchar(30) NOT NULL,
    sort_order  int NOT NULL,
    active      boolean NOT NULL DEFAULT TRUE,
    created_at  timestamptz NOT NULL,
    CONSTRAINT pk_replicate_model PRIMARY KEY (id),
    CONSTRAINT uq_replicate_model_owner_name UNIQUE (owner, name)
);

-- version NULL = "ultima versione" (modelli ufficiali); flux-lora-ff3 e' un fine-tune community e richiede l'hash pinnato.
-- sort_order: il default (primo attivo) resta un modello text-to-image.
INSERT INTO replicate_model (owner, name, version, description, form_type, sort_order, active, created_at) VALUES
    ('sdurz75', 'flux-lora-ff3', '94677f3ac3b39c2d4d86ebea27919f9653684ee9b664662cde3ebee9b52ecbde', NULL, 'FLUX_LORA_FF3', 0, TRUE, CURRENT_TIMESTAMP),
    ('black-forest-labs', 'flux-2-klein-9b', NULL, 'FLUX.2 klein 9B: modello foundation distillato (4 step), inferenza rapida', 'FLUX_2_KLEIN_9B', 1, TRUE, CURRENT_TIMESTAMP),
    ('black-forest-labs', 'flux-krea-dev', NULL, 'FLUX.1 Krea [dev]: modello opinionated di Black Forest Labs/Krea per il fotorealismo', 'FLUX_KREA_DEV', 2, TRUE, CURRENT_TIMESTAMP),
    ('prunaai', 'p-video', NULL, 'P-Video (Pruna AI): video da testo o da immagine, con modalita'' draft', 'P_VIDEO', 3, TRUE, CURRENT_TIMESTAMP),
    ('black-forest-labs', 'flux-kontext-dev', NULL, 'FLUX.1 Kontext [dev]: modifica un''immagine esistente a partire da un prompt', 'FLUX_KONTEXT_DEV', 4, TRUE, CURRENT_TIMESTAMP),
    ('black-forest-labs', 'flux-dev-lora', NULL, 'FLUX.1 [dev] con LoRA caricabili al volo (Replicate, HuggingFace, CivitAI, .safetensors), anche img2img', 'FLUX_DEV_LORA', 5, TRUE, CURRENT_TIMESTAMP);

-- LoRA anagrafati (CRUD /loras, LoraPresetService): preset da scegliere nelle form di flux-dev-lora. Sono solo un aiuto di
-- compilazione (la form riceve comunque testo + scala): nessuna FK da generation.
CREATE TABLE lora_preset (
    id            bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          varchar(60) NOT NULL,
    source        varchar(500) NOT NULL,
    scale         double precision NOT NULL DEFAULT 1,
    trigger_words varchar(500),
    note          varchar(500),
    created_at    timestamptz NOT NULL,
    updated_at    timestamptz NOT NULL,
    CONSTRAINT pk_lora_preset PRIMARY KEY (id),
    CONSTRAINT uq_lora_preset_name UNIQUE (name)
);

-- Il turno di chat (hexa-ai, db/migration/ai) punta all'esito con un riferimento opaco: l'app lo lega alla generazione. ON DELETE SET NULL: il turno resta
-- (testo/ruolo), perde solo il riferimento all'immagine cancellata. La FK sta qui perche' va nella direzione delle dipendenze (app -> ai).
ALTER TABLE chat_message
    ADD CONSTRAINT fk_chat_message_generation FOREIGN KEY (outcome_ref) REFERENCES generation (id) ON DELETE SET NULL;
