-- Registro degli errori delle chiamate remote (Replicate, OpenRouter, SearXNG, storage) e degli
-- errori interni non gestiti, consultabile da /errors. SOURCE e' VARCHAR (non ENUM H2) per non
-- richiedere una migrazione a ogni nuova sorgente. Nessuna FK verso GENERATION/CHAT_CONVERSATION:
-- l'errore deve sopravvivere alla cancellazione dell'entita' a cui si riferisce.
-- Serie: ripetizioni ravvicinate dello stesso errore (SOURCE+OPERATION+GENERATION_ID+ERROR_TYPE)
-- aggiornano OCCURRENCES/LAST_SEEN_AT invece di creare una riga per ogni poll (vedi AppErrorService).
CREATE TABLE "APP_ERROR" (
    "ID"              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "CREATED_AT"      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "LAST_SEEN_AT"    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "OCCURRENCES"     INT NOT NULL,
    "SOURCE"          VARCHAR(20) NOT NULL,
    "OPERATION"       VARCHAR(100) NOT NULL,
    "ERROR_TYPE"      VARCHAR(200) NOT NULL,
    "MESSAGE"         VARCHAR(2000) NOT NULL,
    "DETAILS"         CLOB,
    "GENERATION_ID"   BIGINT,
    "CONVERSATION_ID" BIGINT,
    CONSTRAINT "PK_APP_ERROR" PRIMARY KEY ("ID")
);
CREATE INDEX "IDX_APP_ERROR_LAST_SEEN" ON "APP_ERROR" ("LAST_SEEN_AT");
