-- Schema iniziale: ricalca esattamente le tabelle che Hibernate aveva
-- generato con ddl-auto=update dalle entity Generation/ChatConversation/
-- ChatMessage (nomi tabella/colonna dedotti dalla naming strategy di
-- Spring Boot, tipi estratti da uno SCRIPT reale su H2), cosi' il
-- passaggio a Flyway + ddl-auto=validate non cambia nulla a runtime.

CREATE TABLE "GENERATION" (
    "ID"              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "EXTERNAL_ID"     VARCHAR(255) NOT NULL,
    "MODEL"           VARCHAR(255) NOT NULL,
    "VERSION"         VARCHAR(255),
    "PROMPT"          CLOB NOT NULL,
    "PARAMETERS_JSON" CLOB,
    "STATUS"          ENUM('PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED') NOT NULL,
    "IMAGE_FILENAME"  VARCHAR(255),
    "ERROR_MESSAGE"   CLOB,
    "CREATED_AT"      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "COMPLETED_AT"    TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT "PK_GENERATION" PRIMARY KEY ("ID")
);

CREATE TABLE "CHAT_CONVERSATION" (
    "ID"         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "CREATED_AT" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT "PK_CHAT_CONVERSATION" PRIMARY KEY ("ID")
);

CREATE TABLE "CHAT_MESSAGE" (
    "ID"              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "CONVERSATION_ID" BIGINT NOT NULL,
    "ROLE"            ENUM('USER', 'ASSISTANT') NOT NULL,
    "CONTENT"         CLOB NOT NULL,
    "CREATED_AT"      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT "PK_CHAT_MESSAGE" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_CHAT_MESSAGE_CONVERSATION" FOREIGN KEY ("CONVERSATION_ID")
        REFERENCES "CHAT_CONVERSATION" ("ID")
);
