-- Schema di base su PostgreSQL + pgvector. Sostituisce le migrazioni V1..V23 del periodo H2 (dialetto H2: ENUM, CLOB,
-- identificatori quotati maiuscoli), che su Postgres non girano: il passaggio e' avvenuto SENZA migrare i dati (DB nuovo), quindi
-- lo storico e' stato "squashato" in questo baseline (le versioni originali restano nella storia git). Da qui in avanti vale
-- la regola di sempre: una nuova V<N+1> per ogni modifica di schema, mai modificare un file gia' eseguito.
--
-- Convenzioni: identificatori minuscoli NON quotati (Hibernate non li quota); testo lungo = text; timestamp = timestamptz;
-- gli "enum" Java sono varchar (nessun ENUM/CHECK di DB: un nuovo valore non richiede una migrazione).

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE chat_conversation (
    id         bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title      varchar(255),
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT pk_chat_conversation PRIMARY KEY (id)
);

-- Una Generation avviata da /deep-chat ricorda la conversazione (NULL per il form diretto): serve a ripristinare il placeholder di
-- una generazione ancora in corso al reload. ON DELETE SET NULL: cancellare la conversazione non elimina le generazioni.
-- source_generation_id = generazione sorgente di un img2video ("Anima"), stesso ragionamento. cost_usd = costo stimato (snapshot,
-- NULL se non stimabile). source_upload_filename = immagine caricata per un img2video/edit stand-alone (non e' una Generation).
CREATE TABLE generation (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    external_id            varchar(255) NOT NULL,
    model                  varchar(255) NOT NULL,
    version                varchar(255),
    prompt                 text NOT NULL,
    parameters_json        text,
    seed                   bigint,
    status                 varchar(20) NOT NULL,
    kind                   varchar(10) NOT NULL DEFAULT 'IMAGE',
    error_message          text,
    cost_usd               numeric(12, 6),
    source_generation_id   bigint,
    source_upload_filename varchar(255),
    conversation_id        bigint,
    created_at             timestamptz NOT NULL,
    completed_at           timestamptz,
    CONSTRAINT pk_generation PRIMARY KEY (id),
    CONSTRAINT fk_generation_conversation FOREIGN KEY (conversation_id) REFERENCES chat_conversation (id) ON DELETE SET NULL,
    CONSTRAINT fk_generation_source FOREIGN KEY (source_generation_id) REFERENCES generation (id) ON DELETE SET NULL
);

-- File prodotti da una generazione (ordinati) e file con la star (preferiti, per singolo file).
CREATE TABLE generation_image (
    generation_id bigint NOT NULL,
    ordinal       int NOT NULL,
    filename      varchar(255) NOT NULL,
    CONSTRAINT pk_generation_image PRIMARY KEY (generation_id, ordinal),
    CONSTRAINT fk_generation_image_generation FOREIGN KEY (generation_id) REFERENCES generation (id)
);

CREATE TABLE generation_favourite (
    generation_id bigint NOT NULL,
    filename      varchar(255) NOT NULL,
    CONSTRAINT pk_generation_favourite PRIMARY KEY (generation_id, filename),
    CONSTRAINT fk_generation_favourite_generation FOREIGN KEY (generation_id) REFERENCES generation (id) ON DELETE CASCADE
);

-- generation_id ON DELETE SET NULL: il turno di chat resta (testo/ruolo), perde solo il riferimento all'immagine cancellata.
-- error = turno ASSISTANT di errore (escluso dal contesto inviato all'LLM).
CREATE TABLE chat_message (
    id              bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    conversation_id bigint NOT NULL,
    role            varchar(20) NOT NULL,
    content         text NOT NULL,
    generation_id   bigint,
    error           boolean NOT NULL DEFAULT FALSE,
    created_at      timestamptz NOT NULL,
    CONSTRAINT pk_chat_message PRIMARY KEY (id),
    CONSTRAINT fk_chat_message_conversation FOREIGN KEY (conversation_id) REFERENCES chat_conversation (id),
    CONSTRAINT fk_chat_message_generation FOREIGN KEY (generation_id) REFERENCES generation (id) ON DELETE SET NULL
);

-- Catalogo dei modelli Replicate proposti nelle form. form_type seleziona form/handler Java (GenerationFormType), varchar per non
-- richiedere una migrazione di tipo a ogni nuovo form-type (serve solo l'INSERT del seed).
CREATE TABLE replicate_model (
    id          bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner       varchar(255) NOT NULL,
    name        varchar(255) NOT NULL,
    version     varchar(255),
    description varchar(1024),
    form_type   varchar(30) NOT NULL,
    sort_order  int NOT NULL,
    active      boolean NOT NULL DEFAULT TRUE,
    created_at  timestamptz NOT NULL,
    CONSTRAINT pk_replicate_model PRIMARY KEY (id),
    CONSTRAINT uq_replicate_model_owner_name UNIQUE (owner, name)
);

-- version NULL = "ultima versione" (modelli ufficiali); flux-lora-ff3 e' un fine-tune community e richiede l'hash pinnato.
-- sort_order: il default (primo attivo) resta un modello text-to-image.
INSERT INTO replicate_model (owner, name, version, description, form_type, sort_order, active, created_at) VALUES
    ('sdurz75', 'flux-lora-ff3', '94677f3ac3b39c2d4d86ebea27919f9653684ee9b664662cde3ebee9b52ecbde', NULL, 'FLUX_LORA_FF3', 0, TRUE, CURRENT_TIMESTAMP),
    ('black-forest-labs', 'flux-2-klein-9b', NULL, 'FLUX.2 klein 9B: modello foundation distillato (4 step), inferenza rapida', 'FLUX_2_KLEIN_9B', 1, TRUE, CURRENT_TIMESTAMP),
    ('black-forest-labs', 'flux-krea-dev', NULL, 'FLUX.1 Krea [dev]: modello opinionated di Black Forest Labs/Krea per il fotorealismo', 'FLUX_KREA_DEV', 2, TRUE, CURRENT_TIMESTAMP),
    ('prunaai', 'p-video', NULL, 'P-Video (Pruna AI): video da testo o da immagine, con modalita'' draft', 'P_VIDEO', 3, TRUE, CURRENT_TIMESTAMP),
    ('black-forest-labs', 'flux-kontext-dev', NULL, 'FLUX.1 Kontext [dev]: modifica un''immagine esistente a partire da un prompt', 'FLUX_KONTEXT_DEV', 4, TRUE, CURRENT_TIMESTAMP),
    ('black-forest-labs', 'flux-dev-lora', NULL, 'FLUX.1 [dev] con LoRA caricabili al volo (Replicate, HuggingFace, CivitAI, .safetensors), anche img2img', 'FLUX_DEV_LORA', 5, TRUE, CURRENT_TIMESTAMP);

-- Registro eventi di sistema (errori e avvisi), pagina /system/events. Nessuna FK verso generation/chat_conversation: l'evento deve
-- sopravvivere alla cancellazione dell'entita' a cui si riferisce. Serie = ripetizioni ravvicinate dello stesso evento
-- (occurrences/last_seen_at). subject = a cosa si riferisce (es. 'token:12'); acknowledged_at = visualizzato (campanella).
CREATE TABLE system_event (
    id              bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      timestamptz NOT NULL,
    last_seen_at    timestamptz NOT NULL,
    occurrences     int NOT NULL,
    source          varchar(20) NOT NULL,
    severity        varchar(10) NOT NULL DEFAULT 'ERROR',
    operation       varchar(100) NOT NULL,
    error_type      varchar(200) NOT NULL,
    message         varchar(2000) NOT NULL,
    details         text,
    generation_id   bigint,
    conversation_id bigint,
    subject         varchar(100),
    acknowledged_at timestamptz,
    CONSTRAINT pk_system_event PRIMARY KEY (id)
);
CREATE INDEX idx_system_event_last_seen ON system_event (last_seen_at);
CREATE INDEX idx_system_event_severity ON system_event (severity, last_seen_at);
CREATE INDEX idx_system_event_unseen ON system_event (acknowledged_at, last_seen_at);

-- Token API (CivitAI, HuggingFace) per i LoRA privati: cifrati (SecretCipher), scelti per NOME nelle form. token_hint = ultimi
-- caratteri in chiaro, solo per riconoscerlo nella UI.
CREATE TABLE api_token (
    id              bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    provider        varchar(20) NOT NULL,
    name            varchar(60) NOT NULL,
    token_encrypted bytea NOT NULL,
    token_hint      varchar(8) NOT NULL,
    expires_at      date,
    created_at      timestamptz NOT NULL,
    updated_at      timestamptz NOT NULL,
    CONSTRAINT pk_api_token PRIMARY KEY (id),
    CONSTRAINT uq_api_token_provider_name UNIQUE (provider, name)
);

-- Vector store della ricerca semantica (PgVectorStore di Spring AI, vedi CLAUDE.md "Ricerca semantica"): schema imposto dallo
-- store (id, content, metadata, embedding). id text perche' gli id sono "generation:12", "note:<uuid>". vector(384) = dimensione di
-- multilingual-e5-small: un modello con altre dimensioni richiede una nuova migrazione (ALTER ... TYPE vector(N), dopo aver
-- svuotato la tabella) e la reindicizzazione. NESSUN indice ANN (HNSW/IVFFlat): /search mostra TUTTA la classifica sopra soglia e un
-- indice approssimato tronca i risultati a ef_search (40); lo scan esatto a decine di migliaia di righe costa pochi ms.
-- L'hash del testo, il modello e la data di indicizzazione stanno nei metadata (chiavi riservate, vedi VectorIndexer).
CREATE TABLE vector_store (
    id        text PRIMARY KEY,
    content   text,
    metadata  json,
    embedding vector(384)
);
