-- Token API (CivitAI, HuggingFace) per scaricare LoRA privati: salvati CIFRATI (SecretCipher, stessa chiave e algoritmo dei
-- binari WebDAV), scelti per NOME nelle form di generazione. TOKEN_HINT = ultimi caratteri in chiaro, solo per riconoscerlo
-- nella UI. EXPIRES_AT e' inserita a mano (nessuno dei due servizi la espone in modo affidabile). Nessuna FK verso le
-- generazioni: PARAMETERS_JSON conserva solo l'id scelto. PROVIDER come VARCHAR (non ENUM H2), come SOURCE di SYSTEM_EVENT.
CREATE TABLE "API_TOKEN" (
    "ID"              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "PROVIDER"        VARCHAR(20)  NOT NULL,
    "NAME"            VARCHAR(60)  NOT NULL,
    "TOKEN_ENCRYPTED" VARBINARY(1024) NOT NULL,
    "TOKEN_HINT"      VARCHAR(8)   NOT NULL,
    "EXPIRES_AT"      DATE,
    "CREATED_AT"      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "UPDATED_AT"      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT "PK_API_TOKEN" PRIMARY KEY ("ID"),
    CONSTRAINT "UQ_API_TOKEN_PROVIDER_NAME" UNIQUE ("PROVIDER", "NAME")
);
