-- LoRA anagrafati (CRUD /loras, LoraPresetService): preset da scegliere nelle form di flux-dev-lora. Sono solo un aiuto di
-- compilazione (la form riceve comunque testo + scala): nessuna FK da generation.
CREATE TABLE lora_preset (
    id            bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          varchar(60) NOT NULL,
    source        varchar(500) NOT NULL,
    scale         double precision NOT NULL DEFAULT 1,
    trigger_words varchar(500),
    note          varchar(500),
    created_at    timestamptz NOT NULL,
    updated_at    timestamptz NOT NULL,
    CONSTRAINT pk_lora_preset PRIMARY KEY (id),
    CONSTRAINT uq_lora_preset_name UNIQUE (name)
);
