-- Persistenza della cronologia di /deep-chat (vedi CLAUDE.md, punto 3
-- dello Scopo, "non ancora implementato" fino a qui). Un'unica
-- conversazione continua, non multi-utente (come il resto dell'app:
-- GENERATION non ha un owner): niente tabella CHAT_CONVERSATION
-- separata come nello schema rimosso in V2, basta l'elenco messaggi,
-- azzerabile per intero dal controllo di reset in UI.
CREATE TABLE "CHAT_MESSAGE" (
    "ID"            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "ROLE"          ENUM('USER', 'AI') NOT NULL,
    "CONTENT"       CLOB NOT NULL,
    "GENERATION_ID" BIGINT,
    "CREATED_AT"    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT "PK_CHAT_MESSAGE" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_CHAT_MESSAGE_GENERATION" FOREIGN KEY ("GENERATION_ID")
        REFERENCES "GENERATION" ("ID")
);
