-- /deep-chat supporta ora piu' conversazioni (elencabili/rinominabili/
-- eliminabili dalla sidebar), non piu' un'unica cronologia globale:
-- CHAT_MESSAGE guadagna un CONVERSATION_ID verso una nuova
-- CHAT_CONVERSATION (titolo rinominabile, NULLABLE - quando null il
-- titolo mostrato e' calcolato lato applicazione dal primo turno utente
-- o da un fallback i18n, mai una stringa di default persistita qui,
-- vedi ChatConversation).
--
-- Backfill: come gia' fatto in V4 (mai come in V2, che eliminava dati
-- di una feature ormai morta), le righe CHAT_MESSAGE gia' esistenti
-- vanno preservate, non scartate. Se la tabella ha gia' righe, viene
-- creata UNA conversazione "contenitore" con created_at/updated_at
-- presi dal range dei messaggi esistenti, a cui vengono agganciati
-- tutti. Se CHAT_MESSAGE e' vuota (es. azzerata da un reset), un
-- MIN/MAX senza GROUP BY restituirebbe comunque UNA riga di soli NULL
-- anche su zero righe sorgente: si filtra quindi sul risultato gia'
-- aggregato (sottoquery + WHERE IS NOT NULL), cosi' la INSERT non
-- inserisce nulla in quel caso, invece di una riga con timestamp NULL
-- che violerebbe i vincoli NOT NULL sotto.
CREATE TABLE "CHAT_CONVERSATION" (
    "ID"         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TITLE"      VARCHAR(255),
    "CREATED_AT" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "UPDATED_AT" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT "PK_CHAT_CONVERSATION" PRIMARY KEY ("ID")
);

INSERT INTO "CHAT_CONVERSATION" ("TITLE", "CREATED_AT", "UPDATED_AT")
SELECT NULL, "MIN_CREATED", "MAX_CREATED"
FROM (SELECT MIN("CREATED_AT") AS "MIN_CREATED", MAX("CREATED_AT") AS "MAX_CREATED"
      FROM "CHAT_MESSAGE") "AGG"
WHERE "MIN_CREATED" IS NOT NULL;

ALTER TABLE "CHAT_MESSAGE" ADD COLUMN "CONVERSATION_ID" BIGINT;

UPDATE "CHAT_MESSAGE" SET "CONVERSATION_ID" = (SELECT MIN("ID") FROM "CHAT_CONVERSATION");

ALTER TABLE "CHAT_MESSAGE" ALTER COLUMN "CONVERSATION_ID" SET NOT NULL;

ALTER TABLE "CHAT_MESSAGE" ADD CONSTRAINT "FK_CHAT_MESSAGE_CONVERSATION" FOREIGN KEY ("CONVERSATION_ID")
    REFERENCES "CHAT_CONVERSATION" ("ID");
