-- Catalogo dei modelli Replicate proposti nel combobox di /generations/new
-- e /deep-chat: censito a mano (INSERT sotto), non piu' fetchato dal vivo
-- da Replicate a ogni avvio (vedi ReplicateModelCatalog; CollectionResponse/
-- ReplicateModelSummary/ReplicateClient.getCollection/getModel rimossi).
-- FORM_TYPE seleziona quale fragment/handler Java gestisce i parametri di
-- generazione per quel modello (vedi GenerationFormType/
-- GenerationParameterHandler): un solo valore oggi perche' un solo modello
-- e' censito, l'ENUM va esteso con una migrazione quando se ne aggiunge un
-- altro con una form diversa.
CREATE TABLE "REPLICATE_MODEL" (
    "ID"          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OWNER"       VARCHAR(255) NOT NULL,
    "NAME"        VARCHAR(255) NOT NULL,
    "VERSION"     VARCHAR(255),
    "DESCRIPTION" VARCHAR(1024),
    "FORM_TYPE"   ENUM('FLUX_LORA_FF3') NOT NULL,
    "SORT_ORDER"  INT NOT NULL,
    "ACTIVE"      BOOLEAN NOT NULL DEFAULT TRUE,
    "CREATED_AT"  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT "PK_REPLICATE_MODEL" PRIMARY KEY ("ID"),
    CONSTRAINT "UQ_REPLICATE_MODEL_OWNER_NAME" UNIQUE ("OWNER", "NAME")
);

-- VERSION e' l'hash pinnato reale (GET /v1/models/sdurz75/flux-lora-ff3,
-- campo latest_version.id) recuperato una tantum da Replicate al momento
-- di scrivere questa migrazione: non va lasciato NULL, lo shortcut
-- "ultima versione" implicito non e' supportato da questo modello
-- (verificato dal vivo, vedi la vecchia ReplicateModelCatalog).
INSERT INTO "REPLICATE_MODEL" ("OWNER", "NAME", "VERSION", "DESCRIPTION", "FORM_TYPE", "SORT_ORDER", "ACTIVE", "CREATED_AT")
VALUES ('sdurz75', 'flux-lora-ff3', '94677f3ac3b39c2d4d86ebea27919f9653684ee9b664662cde3ebee9b52ecbde', NULL, 'FLUX_LORA_FF3', 0, TRUE, CURRENT_TIMESTAMP);
